name: build images
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NODE_ENV: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Mount Bazel Cache
      uses: actions/cache@v2.1.7
      with: 
        path: |
          /home/runner/.cache/bazel
          dist
          node_modules
        key: ${{ runner.os }}-bazel-${{ github.sha }}
        restore-keys: ${{ runner.os }}-bazel-
    - name: Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '14'
    - name: Setup Dependencies
      run: yarn --production=false --frozen-lockfile
    - name: Run Tests
      run: yarn test
    - name: Run Lint
      run: yarn lint
    - name: Build Container Images
      run: yarn run bazel build //:container_images
    - name: Report Web Bundle Size
      run: |
        echo "::warning file=bundle.js::size: $(numfmt --to=iec-i --suffix=B --format="%.3f" $(stat -c%s dist/bin/src/frontend/web/bundle/bundle.js))"
    - name: Archive Bundle Size Results
      uses: actions/upload-artifact@v2
      with:
        name: bundle-stats
        path: dist/bin/src/frontend/web/bundle/stats*
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Publish Container Images
      run: |
        yarn run bazel run //:publish_web &&
        yarn run bazel run //:publish_envoy &&
        yarn run bazel run //:publish_backend
    - name: Set Up GCloud Cloud SDK Environment
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.VERSIONSTORE_SA }}
        export_default_credentials: true
    - name: Tag the Versionstore Assets
      run: bash -c "echo -n sha-${GITHUB_SHA::8} | gsutil cp - gs://versionstore/apps/metanotes/IMAGE_TAG"
